name: Deploy Email Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/vortex_cursor.pem
        chmod 600 ~/.ssh/vortex_cursor.pem
        
        # Add SSH config
        cat >> ~/.ssh/config <<EOF
        Host cursor-srv
          HostName ${{ secrets.EC2_HOST }}
          User ubuntu
          IdentityFile ~/.ssh/vortex_cursor.pem
          StrictHostKeyChecking no
        EOF
    
    - name: Deploy to server
      run: |
        chmod +x deploy.sh
        ./deploy.sh
    
    - name: Cleanup
      if: always()
      run: |
        rm -f ~/.ssh/vortex_cursor.pem 